### ISSUE TITLE
What is the default editor in this image?

### ISSUE THREAD

**Issue by Ryland0** [linuxserver/docker-smokeping#101]
I do not see a default editor for managing the Targets file. I tried to install nano with **apt** but it is not found. I tried to install with wget but **make** is also not found.

**Comment by aptalca** [comment]
Edit them on host as everything that's user customizable should be in the persistent config folder

**Comment by Ryland0** [comment]
Oh dang, lesson learned. Thank you very much!

**Comment by aptalca** [comment]
For most of our images, you shouldn't ever have to exec into the container and run commands manually and we don't support it (unless we specifically ask you to like in the case of updating nextcloud via cli, but that's rare)
