### ISSUE TITLE
Latest image for arm32v7 - problem with date/time

### ISSUE THREAD

**Issue by cm91** [linuxserver/docker-smokeping#108]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Got the newest image for arm32v7 --> smokeping stopped working.

After some checks i found out, that the date and time is wrong inside the container.

I have the timezone option in my docker-compose file

I also tried with using etc/localtime from the docker host.

------------------------------

## Expected Behavior
Time should be correct

## Current Behavior
Time is always "Thu Jan  1 01:00:00 CET 1970"

## Steps to Reproduce

create a container with the latest arm32 image.

## Environment
**OS: Raspbian 10**
**CPU architecture:** arm32
**How docker service was installed:**

from rasbian repo

## Command used to create docker container (run/create/compose/screenshot)

version: '3'

services:
  smokeping:
    image: linuxserver/smokeping
    restart: always
    container_name: smokeping
    hostname: 'smokeping'
    networks:
      docker-net:
        ipv4_address: "10.41.0.24"

    environment:
        - PGID=114
        - PUID=109
        - TZ=Europe/Berlin

    volumes:
        - /dir/smokeping/data/config:/config
        - /dir/smokeping/data/data:/data
        - 
networks:
  default:
    external:
       name: docker-net
  docker-net:
    external: true

## Docker logs

there are no logs that show an error!

**Comment by Roxedus** [comment]
Your logs does indeed help you. It links you to [this](https://docs.linuxserver.io/faq#libseccomp)

**Comment by cm91** [comment]
Sorry, i missed that, of course you are right!
