### ISSUE TITLE
Make changes so Slave instances can be launched

### ISSUE THREAD

**Issue by gee456** [linuxserver/docker-smokeping#115]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The current container image does not have a way to launch a slave instance for SmokePing.  I have already come up with a single file modification to make this work.

------------------------------

## Desired Behavior

Only file to modify on the image is \etc\services.d\smokeping\run , then I rebuilt it with docker build

\etc\services.d\smokeping\run
```
#!/usr/bin/with-contenv bash

if [ -a /config/MasterUrl ] && [ -a /config/SlaveSecret ]; then
    chmod 600 /config/SlaveSecret
    chmod 600 /config/MasterUrl
    if [ - a /var/smokeping ]; then mkdir /var/smokeping; done
    masterurl=$(cat /config/MasterUrl)
    exec s6-setuidgid abc  /usr/bin/smokeping --master-url=$masterurl --cache-dir=/var/smokeping --shared-secret=/config/SlaveSecret
else
    exec s6-setuidgid abc  /usr/bin/smokeping --config="/etc/smokeping/config" --nodaemon
fi

```
For the Slave container , we just need to create two files in the /config location
create /config/SlaveSecret 
```
####example contents####
remote1secret
```
create /config/MasterUrl
```
####example contents####
http://192.168.55.212/smokeping/smokeping.cgi
```

On the Master container we will will need modify the following files so the slave can communicate

change file /config/Slaves
```
##example content##
secrets=/config/smokeping_secrets
+remote1
display_name=remote1
color=0000ff
```

Create  /config/smokeping_secrets
```
##example content##
remote1:remote1secret
```

Modify /config/Targets to create check criteria for the Slave
```
##example content ##
+ Remote1
menu = Remote1
title = Remote1
slaves = remote1

++ GoogleDNS1
menu = Google DNS 1
title = Google DNS 8.8.8.8
host = 8.8.8.8

++ GoogleDNS2
menu = Google DNS 2
title = Google DNS 8.8.4.4
host = 8.8.4.4
```

Then we need to make sure we launch the slave using the hostname option, the slave will need to be able to each the master url, then everything works as expected
```
###example###
docker run --hostname remote1 -d --name=remote1 -e PUID=1000 -e PGID=1000 -e TZ=America/Chicago -v /srv/remote1:/config --restart unless-stopped   ghcr.io/linuxserver/smokeping
```

## Current Behavior
Cannot get slave to work because you have to specify slave configuration on launch of smokeping

## Alternatives Considered
I could create a fork and use my own image. I think this is good functionality to add.

**Comment by gee456** [comment]
please keep open

**Comment by j0nnymoe** [comment]
If you want to make a PR for this, we can review it.

**Comment by HaoZhuzZ** [comment]
@gee456 In this file "\etc\services.d\smokeping\run", this line :
if [ - a /var/smokeping ]; then mkdir /var/smokeping; done

should be
if [ ! -a /var/smokeping ]; then mkdir /var/smokeping; done
