### ISSUE TITLE
All of a sudden it stopped working

### ISSUE THREAD

**Issue by hufhend** [linuxserver/docker-smokeping#121]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
All of a sudden Smokeping from docker hub started via docker compose stopped working. It worked before. On different machines. Now it doesn't work anywhere. I tried to build the container directly and it doesn't work either. 

## Current Behavior
It can't be assembled at all

## Steps to Reproduce
1. git clone https://github.com/linuxserver/docker-smokeping.git
2. docker build -t smokeping .

## Environment
**OS:** Ubuntu Linux 20.04.3 LTS
**CPU architecture:** x86_64/arm64
**How docker service was installed:** Docker version 20.10.12, build e91ed57

## Command used to create docker container (run/create/compose/screenshot)
docker build -t smokeping .

## Docker logs
Sending build context to Docker daemon  155.6kB
Step 1/11 : FROM ghcr.io/linuxserver/baseimage-alpine:3.13
3.13: Pulling from linuxserver/baseimage-alpine
b9287f8b6413: Pull complete 
41a58871f1ed: Pull complete 
a5ef121ca2e1: Pull complete 
9095bf73568f: Pull complete 
adac643cc697: Pull complete 
ee44e1918feb: Pull complete 
Digest: sha256:5257ba193e0e29cd1cad0ffb7dc2206cf738d2cf8cfbc097d9102fcf26d158a8
Status: Downloaded newer image for ghcr.io/linuxserver/baseimage-alpine:3.13
 ---> 40ae7b5025c9
Step 2/11 : ARG BUILD_DATE
 ---> Running in e0fddd14ddc2
Removing intermediate container e0fddd14ddc2
 ---> b757ef0677dd
Step 3/11 : ARG VERSION
 ---> Running in ab4063206895
Removing intermediate container ab4063206895
 ---> 00bfb110d7c6
Step 4/11 : ARG SMOKEPING_VERSION
 ---> Running in 5d24b25cb3a6
Removing intermediate container 5d24b25cb3a6
 ---> 1cdac1cab10e
Step 5/11 : LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
 ---> Running in b22fd2316651
Removing intermediate container b22fd2316651
 ---> 5650ae6ae508
Step 6/11 : LABEL maintainer="ironicbadger,sparklyballs"
 ---> Running in b96a4540a092
Removing intermediate container b96a4540a092
 ---> d5040cf4538e
Step 7/11 : COPY tcpping /defaults/
 ---> ec0d354f7acb
Step 8/11 : RUN  echo "**** install packages ****" &&  if [ -z ${SMOKEPING_VERSION+x} ]; then 	SMOKEPING_VERSION=$(curl -sL "http://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz" | tar -xz -C /tmp 	&& awk '/^P:smokeping$/,/V:/' /tmp/APKINDEX | sed -n 2p | sed 's/^V://');  fi &&  apk add --no-cache 	apache2 	apache2-ctl 	apache2-utils 	apache-mod-fcgid 	bc 	bind-tools 	curl 	font-noto-cjk 	openssh-client 	smokeping==${SMOKEPING_VERSION} 	ssmtp 	sudo 	tcptraceroute 	ttf-dejavu &&  echo "**** give setuid access to traceroute & tcptraceroute ****" &&  chmod a+s /usr/bin/traceroute &&  chmod a+s /usr/bin/tcptraceroute &&  echo "**** fix path to cropper.js ****" &&  sed -i 's#src="/cropper/#/src="cropper/#' /etc/smokeping/basepage.html &&  echo "**** install tcping script ****" &&  install -m755 -D /defaults/tcpping /usr/bin/ &&  echo "**** remove default apache conf ****" &&  rm -f /etc/apache2/httpd.conf
 ---> Running in 1bdb1c1f1ecd
**** install packages ****
/bin/sh: curl: not found
tar: invalid magic
tar: short read
The command '/bin/sh -c echo "**** install packages ****" &&  if [ -z ${SMOKEPING_VERSION+x} ]; then 	SMOKEPING_VERSION=$(curl -sL "http://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz" | tar -xz -C /tmp 	&& awk '/^P:smokeping$/,/V:/' /tmp/APKINDEX | sed -n 2p | sed 's/^V://');  fi &&  apk add --no-cache apache2 	apache2-ctl 	apache2-utils 	apache-mod-fcgid 	bc 	bind-tools 	curl 	font-noto-cjk 	openssh-client 	smokeping==${SMOKEPING_VERSION} 	ssmtp 	sudo 	tcptraceroute 	ttf-dejavu &&  echo "**** give setuid access to traceroute & tcptraceroute ****" &&  chmod a+s /usr/bin/traceroute &&  chmod a+s /usr/bin/tcptraceroute &&  echo "**** fix path to cropper.js ****" &&  sed -i 's#src="/cropper/#/src="cropper/#' /etc/smokeping/basepage.html &&  echo "**** install tcping script ****" &&  install -m755 -D /defaults/tcpping /usr/bin/ &&  echo "**** remove default apache conf ****" &&  rm -f /etc/apache2/httpd.conf' returned a non-zero code: 1

**Comment by hufhend** [comment]
perfect, it worked, it's ready to be assembled

**Comment by hufhend** [comment]
On x86 it's fine, but on aarch64 it didn't work. The modified container from image: ghcr.io/linuxserver/smokeping doesn't work either
I'm not sure of the error this time, but I'm seeing a huge CPU load and unfortunately it's not running.

**Comment by Roxedus** [comment]
Post logs from your arm system

**Comment by hufhend** [comment]
I'm sorry, this is my fault. I uploaded the configuration from a working machine, but not the docker. So I'm going to go fix the paths.

```
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the 'ServerName' directive globally to suppress this message
ERROR: can't open /etc/smokeping/config.d/pathnames: No such file or directory
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the 'ServerName' directive globally to suppress this message
```
