### ISSUE TITLE
Update to 2.8.2 release

### ISSUE THREAD

**Issue by svenvg93** [linuxserver/docker-smokeping#125]
Please update the docker to Smokeping 2.8.2; https://github.com/oetiker/SmokePing/releases/tag/2.8.2

**Comment by TheSpad** [comment]
We currently install from the Alpine package repo and as it stands the latest version available is 2.7.3. Pulling directly from the smokeping github would require a substantial rework of the container.

**Comment by psy0rz** [comment]
https://pkgs.alpinelinux.org/package/edge/main/x86/smokeping#

I tried flaggin it out of date but nothing happens if you press that button it seems?

**Comment by Roxedus** [comment]
Its already flagged, hence the version number in red.

**Comment by dpremy** [comment]
Alpine Edge now has 2.8.2-r2. Unsure when it will be moved to a release, but a new build is in the process of getting to stable.

**Comment by thespad** [comment]
We're not going to rebase the image to Edge, but if Edge is now up-to-date it will be included in Alpine 3.18, which will be released around May time. We can prioritise Smokeping for a rebase to 3.18 to get it updated.
