### ISSUE TITLE
I hope to support the specified ports.

### ISSUE THREAD

**Issue by qingmuhy** [linuxserver/docker-smokeping#128]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I hope it can support specifying the exposed port of webui with environment variables.

## Current Behavior

Now only the port can be specified through the -p parameter, but if you want docker to easily support ipv6, the best way is to use host mode, but port 80 in host mode has long been occupied by other programs.

**Comment by drizuid** [comment]
we have no plans to change things as they are. I use both ipv4 and ipv6 without issue by mapping ports in the supported manner. We do not support using this container in host mode.
