### ISSUE TITLE
usage examples of client

### ISSUE THREAD

**Issue by kkebb** [linuxserver/docker-smokeping#13]
This is not so much an issue more than it is a simple usage request:

Can you show usage examples for turning up clients and configuring the target file accordingly?

**Comment by kkebb** [comment]
ping?

**Comment by j0nnymoe** [comment]
@kkebb sorry for the delayed response, there is information here how to configure the targets file: http://oss.oetiker.ch/smokeping/doc/smokeping_examples.en.html
