### ISSUE TITLE
Doc Request: add instructions on how to reload the configuration

### ISSUE THREAD

**Issue by DeflateAwning** [linuxserver/docker-smokeping#131]
What is the best way to reload the configuration after making changes to the /config/Probes (etc.) files? Just stop and start the Docker container? Or is there a more graceful way?

Put these instructions in the README.

**Comment by DeflateAwning** [comment]
Please address this issue!

**Comment by DeflateAwning** [comment]
Does anyone maintain this project? Why hasn't this been looked at at all?

**Comment by DeflateAwning** [comment]
Can you simply add instructions on how to restart the docker container to reload the configuration then?

**Comment by DeflateAwning** [comment]
Please complete this task.

**Comment by nerdalertdk** [comment]
> The upstream project Smokeping doesn't provide any recommendations on how to gracefully reload the config. In this case I would suggest restarting the container is the easiest way to reload the config.

Smokeping have an reload command, 
https://oss.oetiker.ch/smokeping/doc/smokeping.en.html

Sadly it does not work in this image.

```
root@smokeping:/# smokeping --reload --config=/etc/smokeping/config
### assuming you are using an fping copy reporting in milliseconds
ERROR: Can not read pid from /var/run/smokeping/smokeping.pid: No such file or directory
root@smokeping:/#
```

**Comment by DeflateAwning** [comment]
Great find! Would love to see this issue closed properly by finding out why the `--reload` command doesn't work, and then implementing a command through Docker.

**Comment by aptalca** [comment]
We don't support or recommend running manual commands inside the containers unless we ask you to. It can lead to broken configs that are too difficult to troubleshoot. The recommendation is to restart the container.

If you're using this docker container, we assume you have the basic knowledge on docker commands like `docker restart blah` so we won't be adding that into the container readme as it would be out of scope.

For advanced users, (again, directly interacting with this is unsupported by us), this is the service command that starts and runs smokeping inside the container: https://github.com/linuxserver/docker-smokeping/blob/master/root/etc/services.d/smokeping/run#L3

**Comment by DeflateAwning** [comment]
Thank you! I'm going to submit a PR to the README with this info!

**Comment by DeflateAwning** [comment]
Hmm this didn't work for me:
`docker exec smokeping s6-svc -h /run/service/svc-smokeping`

Are you sure that it worked for you, if you say, added a new target and then ran this command to reload the config?

**Comment by lbogdan** [comment]
Indeed, `smokeping` reloads the config and starts collecting data for the new target (you can check that with `tcpdump`, you should see ICMP packets going to the target host), BUT the `smokeping_cgi` script, which is serving the pages, is separate and controlled by `apache`, and it continues running with the old config.

So new approach - because they're both running with `perl`, you can restart them both with:

```
docker exec $CID killall -HUP perl
```

Just tested this when adding a new target, and it worked fine.

**Comment by DeflateAwning** [comment]
Doing that on all perl processes running seems like bad practice. Is there a way to specify the actual two process names?

**Comment by DeflateAwning** [comment]
What if someone's custom probe uses a perl script? Not likely, but still possible.

**Comment by lbogdan** [comment]
Do you mean a Docker healthcheck?

Even so, that would run for a few milliseconds, and the probability of running the `killall` while the healthcheck is also running is very low. And even if you did, by default Docker waits for 3 consecutive healthcheck failures.

**Comment by thespad** [comment]
Just to step in here for a moment; with the experience we have of how users make use of our documentation we're not going to include anything with scope for unintended consequences when blindly copy/pasted by someone with no understanding of the underlying command(s).

Sending a signal to a specific service or process is fine, sending it to all perl processes in the expectation that nothing current or future will be negatively impacted, is not.

**Comment by DeflateAwning** [comment]
> Do you mean a Docker healthcheck?

No, I mean a custom `smokeping` Probe instance, which is effectively a script which runs to check the uptime of a Target.

**Comment by lbogdan** [comment]
Oh, I see, a Smokeping probe!

Well, today I learned about `pkill`:

```sh
pkill -f -HUP '/usr/bin/perl /usr/s?bin/smokeping(_cgi)?'
```

**Comment by DeflateAwning** [comment]
This one works well! Updated the PR branch. Hopefully someone can merge it!
