### ISSUE TITLE
Trying to use the IRTT probe gives error

### ISSUE THREAD

**Issue by tslura** [linuxserver/docker-smokeping#133]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Using the latest image per 8 Aug 2022

root@gnafle:~# cat /opt/docker-compose.yml
---
version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/smokeping:/config
      - /opt/smokeping:/data
    ports:
      - 80:80
    restart: unless-stopped

------------------------------

## Expected Behavior
The config check should be Okay

## Current Behavior
Config check failes

## Steps to Reproduce

1. Set IRTT in Probes
 +IRTT

 binary = /config/irtt # mandatory
 forks = 5
 offset = 50%
 step = 300
 timeout = 15
 tmpdir = /tmp/smokeping-irtt

 length = 172

2. Set a target that used that probe
3. run config check. IRTT.pm lacks some Perl modules.

root@a92439d422b4:/config# /usr/bin/smokeping --config=/etc/smokeping/config --check
require Smokeping::probes::IRTT failed: Can't locate Path/Tiny.pm in @INC (you may need to install the Path::Tiny module) (@INC contains: .. /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/vendor_perl/Smokeping/probes/IRTT.pm line 22, <$fh> line 18.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Smokeping/probes/IRTT.pm line 22, <$fh> line 18.
Compilation failed in require at (eval 62) line 1, <$fh> line 18.

**Comment by drizuid** [comment]
can you test by doing 
`docker exec -it smokeping apk add --no-cache perl-path-tiny`
and seeing if the IRTT probe works? if it does, we can pretty easily correct this.
