### ISSUE TITLE
I can't access the app page - Returns Internal Server Error

### ISSUE THREAD

**Issue by mrvalterhugo** [linuxserver/docker-smokeping#134]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Access smokeping page.

## Current Behavior

I am not able to access smokeping page.
It takes sometime to load, and return this error:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at you@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

## Steps to Reproduce
I am using the following docker compose:

## Environment
**OS:** Linux Debian 5.10.0-0.bpo.3-amd64
**CPU architecture:** x86_64
**How docker service was installed:**
from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
The docker compose file lives inside /home/myuser/configs/smokeping

---
version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8081:80
    restart: unless-stopped

docker-compose up -d

## Docker logs
smokeping    | [custom-init] no custom services found, skipping...
smokeping    | s6-rc: info: service s6rc-oneshot-runner: starting
smokeping    | s6-rc: info: service s6rc-oneshot-runner successfully started
smokeping    | s6-rc: info: service fix-attrs: starting
smokeping    | s6-rc: info: service 00-legacy: starting
smokeping    | s6-rc: info: service 00-legacy successfully started
smokeping    | s6-rc: info: service fix-attrs successfully started
smokeping    | s6-rc: info: service legacy-cont-init: starting
smokeping    | cont-init: info: running /etc/cont-init.d/01-envfile
smokeping    | cont-init: info: /etc/cont-init.d/01-envfile exited 0
smokeping    | cont-init: info: running /etc/cont-init.d/02-tamper-check
smokeping    | cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
smokeping    | cont-init: info: running /etc/cont-init.d/10-adduser
smokeping    | 
smokeping    | -------------------------------------
smokeping    |           _         ()
smokeping    |          | |  ___   _    __
smokeping    |          | | / __| | |  /  \
smokeping    |          | | \__ \ | | | () |
smokeping    |          |_| |___/ |_|  \__/
smokeping    | 
smokeping    | 
smokeping    | Brought to you by linuxserver.io
smokeping    | -------------------------------------
smokeping    | 
smokeping    | To support LSIO projects visit:
smokeping    | https://www.linuxserver.io/donate/
smokeping    | -------------------------------------
smokeping    | GID/UID
smokeping    | -------------------------------------
smokeping    | 
smokeping    | User uid:    1000
smokeping    | User gid:    1000
smokeping    | -------------------------------------
smokeping    | 
smokeping    | cont-init: info: /etc/cont-init.d/10-adduser exited 0
smokeping    | cont-init: info: running /etc/cont-init.d/30-config
smokeping    | 'Alerts' -> '/config/Alerts'
smokeping    | 'Database' -> '/config/Database'
smokeping    | 'General' -> '/config/General'
smokeping    | 'Presentation' -> '/config/Presentation'
smokeping    | 'Probes' -> '/config/Probes'
smokeping    | 'Slaves' -> '/config/Slaves'
smokeping    | 'Targets' -> '/config/Targets'
smokeping    | 'pathnames' -> '/config/pathnames'
smokeping    | 'ssmtp.conf' -> '/config/ssmtp.conf'
smokeping    | cont-init: info: /etc/cont-init.d/30-config exited 0
smokeping    | cont-init: info: running /etc/cont-init.d/90-custom-folders
smokeping    | cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
smokeping    | cont-init: info: running /etc/cont-init.d/99-custom-files
smokeping    | [custom-init] no custom files found, skipping...
smokeping    | cont-init: info: /etc/cont-init.d/99-custom-files exited 0
smokeping    | s6-rc: info: service legacy-cont-init successfully started
smokeping    | s6-rc: info: service init-mods: starting
smokeping    | s6-rc: info: service init-mods successfully started
smokeping    | s6-rc: info: service init-mods-package-install: starting
smokeping    | s6-rc: info: service init-mods-package-install successfully started
smokeping    | s6-rc: info: service init-mods-end: starting
smokeping    | s6-rc: info: service init-mods-end successfully started
smokeping    | s6-rc: info: service init-services: starting
smokeping    | s6-rc: info: service init-services successfully started
smokeping    | s6-rc: info: service legacy-services: starting
smokeping    | services-up: info: copying legacy longrun apache (no readiness notification)
smokeping    | services-up: info: copying legacy longrun smokeping (no readiness notification)
smokeping    | s6-rc: info: service legacy-services successfully started
smokeping    | s6-rc: info: service 99-ci-service-check: starting
smokeping    | [ls.io-init] done.
smokeping    | s6-rc: info: service 99-ci-service-check successfully started
smokeping    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.26. Set the 'ServerName' directive globally to suppress this message

I have also found this logs i Apache:

root@ae357c0e074b:/# cat /var/log/apache2/error.log 
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.26. Set the 'ServerName' directive globally to suppress this message
[Thu Sep 15 13:09:13.778984 2022] [mpm_prefork:notice] [pid 158] AH00163: Apache/2.4.54 (Unix) mod_fcgid/2.3.9 configured -- resuming normal operations
[Thu Sep 15 13:09:13.779053 2022] [core:notice] [pid 158] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Sep 15 13:10:05.708835 2022] [fcgid:warn] [pid 160] [client 172.20.0.1:46162] mod_fcgid: read data timeout in 40 seconds
[Thu Sep 15 13:10:05.708920 2022] [core:error] [pid 160] [client 172.20.0.1:46162] End of script output before headers: smokeping.cgi

Thanks for any help!

**Comment by ironicbadger** [comment]
The app is hosted internally at `https://smokeping.yourdomain.com/smokeping/smokeping.cgi`.

The readme should probably reflect this.

**Comment by ironicbadger** [comment]
PR opened to attempt to resolve.

**Comment by homerr** [comment]
Resolved with PR & stale.
