### ISSUE TITLE
Cannot run as root user

### ISSUE THREAD

**Issue by magicdude4eva** [linuxserver/docker-smokeping#14]
Did a standard install on Synology via:

```
docker pull linuxserver/smokeping

docker create \
    --name smokeping \
    -p 9500:80 \
    -e PUID=0 -e PGID=101 \
    -e TZ=Africa/Johannesburg \
    -v /volume1/docker/smokeping/data:/data \
    -v /volume1/docker/smokeping/config:/config \
    linuxserver/smokeping
```

and get error when starting up:
```
AH00526: Syntax error on line 175 of /etc/apache2/httpd.conf:
Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
```

Line 175 shows:
```
<IfModule unixd_module>
#
# If you wish httpd to run as a different user or group, you must run
# httpd as root initially and it will switch.
#
# User/Group: The name (or #number) of the user/group to run httpd as.
# It is usually good practice to create a dedicated user and group for
# running httpd, as with most system services.
#
User abc
Group abc

</IfModule>
```

When changing the above to
```
User apache
Group apache

```

and doing an apachectl -t
```
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.20. Set the 'ServerName' directive globally to suppress this message

```

I also needed to change ownership to avoid error `WARNING: creating /var/cache/smokeping/rrdtool.png: Permission denied: /var/www/localhost/smokeping/smokeping.cgi`
```
chown apache:apache /var/cache/smokeping/
```

**Comment by sparklyballs** [comment]
we don't recommend running any of our containers as root.

**Comment by magicdude4eva** [comment]
I don't agree with the comment, as the docker template provides the wrong configuration. The httpd.conf should really contain User/Group apache and not "abc".

It should also have the correct ownership permission for /var/cache. If this needs to be manually configured, I would suggest updating documentation on https://hub.docker.com/r/linuxserver/smokeping/.

FWIW: None of the other docker I am using on Synology require manual configuration of /etc/ files.

**Comment by sparklyballs** [comment]
template ?

the httpd.conf 

`User/Group: The name (or #number) of the user/group to run httpd as.
# It is usually good practice to create a dedicated user and group for
# running httpd, as with most system services.`

in this instance abc provides the same requirement as apache would do.
in a manually installed instance of apache , you'd have to create the user and group, and you can effectively call it whatever you like, apache is used merely as a shorthand to know which app it is specific to in a normal multi-app , multi-user host environment.

**Comment by magicdude4eva** [comment]
I will close this and comment on LinuxServer.io for a solution as it does not sound like this will be fixed. I full understand the error messages and how to fix the issues, my point is that anyone wanting to use this docker image will still need to change the http config and then also adjust permissions of the /var/cache folder. 

Both changes are unnecessary as this could have been addressed as part of the creation of the docker container and would avoid users having to manually make the changes. (Especially since the apache user/group already exists).

**Comment by phendryx** [comment]
That's simply not true. The name and group inside the container don't matter. The PUID and PGID passed into the container do matter. Change the PUID to a non root user and your issues go away. The container is not broken.

**Comment by aptalca** [comment]
@magicdude4eva You need to understand that whatever you set `-e PUID=` to is whatever the user abc inside the container runs as. And apache runs as user abc. In other words, with that variable you control what user id apache runs as. You currently have abc set to 0, which is root. Apache does not like running as root and complains. That's what sparklyballs meant by not recommending running as root.

If you change the line in your docker run command to something like `-e PUID=100` or whatever your synology user's id is, it should work just fine, and all the files owned by the container will be owned by your synology user and you won't have any permission issues.

**Comment by magicdude4eva** [comment]
@aptalca thanks for that explanation - this makes sense. will create a separate non-root user on Synology and pass in another PUID/PGID.
