### ISSUE TITLE
[BUG] No Chart Data 

### ISSUE THREAD

**Issue by Maynardnaze** [linuxserver/docker-smokeping#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Blank Charts in default Internet Sites. Waited 24 hours with no change. DNS Probe charts work fine.
Tried it on Ubuntu 22, 20, RPI 4, Blank VMs in Proxmox, even cloud VPS just for kicks.

### Expected Behavior

Charts to work. 

### Steps To Reproduce

Any Docker install.
legit copy and pasted with change to path

version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/smokeping/config:/config
      - /path/to/smokeping/data:/data
    ports:
      - 80:80
    restart: unless-stopped

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 192.168.90.112. Set the 'ServerName' directive globally to suppress this message
[ls.io-init] done.
WARNING: Hostname 'ipv6.google.com' does currently not resolve to an IPv4 address
### assuming you are using an fping copy reporting in milliseconds
Smokeping version 2.007003 successfully launched.
Entering multiprocess mode.
No targets defined for probe TCPPing, skipping.
Child process 190 started for probe FPing.
FPing: probing 25 targets with step 300 s and offset 172 s.
Child process 191 started for probe DNS.
DNS: probing 9 targets with step 300 s and offset 212 s.
Child process 192 started for probe FPing6.
All probe processes started successfully.
FPing6: probing 1 targets with step 300 s and offset 71 s.

### Environment

```markdown
- OS: Ubuntu 22, 20, Raspbian OS, Debian 11 Kali.
- How docker service was installed: 
Curl and manual. Tried it on 5 different machines

All Archs
32 and 64 bit Arm
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up
```

### Container logs

```bash
Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 192.168.90.112. Set the 'ServerName' directive globally to suppress this message
[ls.io-init] done.
WARNING: Hostname 'ipv6.google.com' does currently not resolve to an IPv4 address
### parsing dig output...OK
### assuming you are using an tcpping copy reporting in milliseconds
### assuming you are using an fping copy reporting in milliseconds
### assuming you are using an fping copy reporting in milliseconds
Smokeping version 2.007003 successfully launched.
Entering multiprocess mode.
No targets defined for probe TCPPing, skipping.
Child process 190 started for probe FPing.
FPing: probing 25 targets with step 300 s and offset 172 s.
Child process 191 started for probe DNS.
DNS: probing 9 targets with step 300 s and offset 212 s.
Child process 192 started for probe FPing6.
All probe processes started successfully.
FPing6: probing 1 targets with step 300 s and offset 71 s.
```

**Comment by xPLAYRZx** [comment]
I'm also seeing the same problem described by OP. DNS Probe charts work fine but FPing charts are empty.

**Comment by tylerpace** [comment]
If smokeping is reporting DNS data, but **not** ping data, then Issue #124 has a potential solution.

**Comment by icetail** [comment]
I'm also seeing the same problem described by OP. DNS Probe charts work fine but FPing charts are empty.
The potential solution does not work for me.

**Comment by gareth-c** [comment]
Same issue, DNSProbe works and FPing stopped working in March

**Comment by xPLAYRZx** [comment]
> If smokeping is reporting DNS data, but **not** ping data, then Issue #124 has a potential solution.

Unfortunately, steps here didn't fix for me either.

**Comment by icetail** [comment]
Pulled a clean image today on my k3s raspberry cluster and it starting working again
