### ISSUE TITLE
[FEAT] add echoping

### ISSUE THREAD

**Issue by scottini** [linuxserver/docker-smokeping#144]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to use echoping as a probe in smokeping, for webservers' monitoring

### Reason for change

It seems to be the best tool for this kind of monitoring, mainly because of the ability to use http and icp instead of tcp or udp echo

**Comment by dpremy** [comment]
See issue #20 and #116, this has been requested before and made no progress.
As echoping is a 'stale project', it's not in Alpine repos, and there are past responses to getting echoping added, it seems unlikely anyone will add it to this container.

It does seem that many of the core smokeping features are missing, and that this container only supports the most basic features. I see pull and feature requests to enhance it, but the bot allows for them to be marked as stale and go unresolved.
