### ISSUE TITLE
[BUG] confusing version numbers

### ISSUE THREAD

**Issue by bartsiek** [linuxserver/docker-smokeping#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running "latest" container from hub.docker.com

Log mentions
`Smokeping version 2.007003 successfully launched.`

Web UI mentions

`Running on [SmokePing-2.7.3](https://oss.oetiker.ch/smokeping/counter.cgi/2.007003) by [Tobi Oetiker](https://tobi.oetiker.ch/) and Niko TyniMaintained by [LinuxServer.io](mailto:ironicbadger@linuxserver.io)`

Link goes to `https://oss.oetiker.ch/smokeping/counter.cgi/*2.007003*`

 

### Expected Behavior

Show aligned version in both logs and webinterface.
Show correct link.

### Steps To Reproduce

1. search linuxserver/smokeping image using Registry 
2. select tag Latest
3. launch new instance
4. map volumes /data and /config
5. set PGID/PUID to run as regular user in s6
6. start container 

### Environment

```markdown
- OS: Synology
- How docker service was installed: GUI synology
```

### CPU architecture

x86-64

### Docker creation

```bash
from docker images --digests:
linuxserver/smokeping             latest       sha256:22430d68c806bc4f43244ce40b9219368694071f5a1252277a461975845c652f   34a333a5357d   3 days ago      221MB
```

### Container logs

```bash
<LSIO logo + text here>
───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1026
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.4. Set the 'ServerName' directive globally to suppress this message
[ls.io-init] done.
### parsing dig output...OK
Smokeping version 2.007003 successfully launched.
Entering multiprocess mode.
Child process 173 started for probe DNS.
Child process 174 started for probe FPing.
All probe processes started successfully.
DNS: probing 3 targets with step 300 s and offset 150 s.
FPing: probing 28 targets with step 300 s and offset 246 s.
```

**Comment by thespad** [comment]
Upstream versions as 2.7.3: 
https://github.com/linuxserver/docker-smokeping/blob/master/package_versions.txt#L152
https://oss.oetiker.ch/smokeping/stats.en.html

The fact that they *also* reference it as `2.007003` in the logs doesn't change that. We can't control how they display version output.

**Comment by drizuid** [comment]
closing as we do not control what the devs of smokeping do with version numbers
