### ISSUE TITLE
Is it possible to include a more recent version of Smokeping?

### ISSUE THREAD

**Issue by magicdude4eva** [linuxserver/docker-smokeping#15]
I have just installed the docker image on OS X and noticed that the RRD 180 value limit fix from 2015 was not applied - see here: https://github.com/oetiker/SmokePing/commit/60419834f224a0735094fd4ad0aac8eac3b15289

Is it possible to include a more recent version of Smokeping?

**Comment by sparklyballs** [comment]
there is no more recent version than what is currently available in the alpine repository and also incidentally ubuntu xenial.

both repositories have the most recent release which is shown [here](https://github.com/oetiker/SmokePing/releases) as 2.6.11

**Comment by magicdude4eva** [comment]
No chance to do a checkout from Github instead? - i.e. the bug fix was committed in June 2015.

The SmokePing Github project has frequent commits - https://github.com/oetiker/SmokePing/commits/master

**Comment by IronicBadger** [comment]
@magicdude4eva please feel free to submit a PR for an 'unstable' tag of the container to do just this
