### ISSUE TITLE
Change the url

### ISSUE THREAD

**Issue by typechoblog** [linuxserver/docker-smokeping#152]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

When I visit the docker smokeping, service url is `http://192.168.1.1:81/smokeping/smokeping.cgi `how to make the url change `http://192.168.1.1:81/smokeping.cgi` (hide the smokeping). My English is not very good. That's what I'm trying to say,sorry :(

### Reason for change

Once I've configured the master/slave for it, I just need to remember the domain name.

### Proposed code change

I don't know how to change.   I'm sorry

**Comment by drizuid** [comment]
This is something you would do on a reverse proxy or the app dev would do it themselves. We manage the container, not the app.
