### ISSUE TITLE
favicon missing from basepage.html ?

### ISSUE THREAD

**Issue by luckman212** [linuxserver/docker-smokeping#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I deploy this docker-smokeping image, the container does not contain the latest [basepage.html][0], with a favicon.

This is a minor issue, but helps to quickly identify the site in bookmarks or open tabs, so is genuinely useful.

I have noticed this behavior for several months, and as of the latest release `2.8.2-r2-ls66`

![screenshot_LFcqtGbM](https://github.com/linuxserver/docker-smokeping/assets/1992842/01a0515f-1f16-44ee-95e5-f16cc5c6cb3f)

vs (where I hand-edited the file to add the base64 encoded favicon from [this commit][1])

![image](https://github.com/linuxserver/docker-smokeping/assets/1992842/6b43042b-9c86-444e-b180-9e6c2bdee16c)

[0]: https://github.com/oetiker/SmokePing/blob/master/etc/basepage.html.dist
[1]: https://github.com/oetiker/SmokePing/commit/0216fe558ce9ab2a8cea47144be2baf8144da36e

### Steps To Reproduce

1. deploy docker image
2. visit page
3. inspect icon...

### Environment

```markdown
- OS: Ubuntu 22.04.3
- Docker installed via snap
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
--name smokeping \
-p 8080:80 \
-v /var/snap/docker/common/var-lib-docker/volumes/smokeping/config:/config \
-v /var/snap/docker/common/var-lib-docker/volumes/smokeping/data:/data \
-v /var/snap/docker/common/var-lib-docker/volumes/smokeping/cache:/var/cache/smokeping \
-e TZ='America/New_York' \
linuxserver/smokeping
```

**Comment by luckman212** [comment]
Hello, is this issue being rejected? I saw the comment about it being invalid but I believe I have provided all the necessary info.

I updated to the `2.8.2-r2-ls70` tag but the issue remains.

**Comment by j0nnymoe** [comment]
Smokeping haven't cut a release since August 2021 and that looks like it was added 11 months ago.
