### ISSUE TITLE
[BUG] Default included Target of linuxserver.io no longer allows pings

### ISSUE THREAD

**Issue by louispires** [linuxserver/docker-smokeping#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The default included Target of linuxserver.io no longer functions and thus serves no purpose.

Possibly provide an alternative link which does allow Pings and update the repo to the new value.

Pings stopped on **15 August 2023 12:00**:
![image](https://github.com/linuxserver/docker-smokeping/assets/8841644/f8dd24fa-3902-4744-bc83-1351f549c780)

### Expected Behavior

I expect the default included config to function like it used to:
![image](https://github.com/linuxserver/docker-smokeping/assets/8841644/919b81b6-36ad-4001-ab9f-edf1a390f48d)

### Steps To Reproduce

1. Install default config
2. Navigate to Internet Sites -> linuxserver.io
3. Graphs are empty since **15 August 2023 12:00**

### Environment

```markdown
- OS: Unraid 6.12.6
- How docker service was installed: Unraid Apps
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid Apps
```

### Container logs

```bash
██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
### parsing dig output...OK
```

**Comment by thespad** [comment]
Oops, ping must have broken when we migrated the site to a new host a few months ago. I've fixed the firewalling so ping to linuxserver.io should work again now.
