### ISSUE TITLE
[FEAT] InfluxDB support

### ISSUE THREAD

**Issue by sartoricz** [linuxserver/docker-smokeping#172]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Would you kindly add InfluxDB::HTTP perl module to the docker file?
I'm trying to export data into an Influx database and it is failing with 
DBG: Setting up a new InfluxDB connection
ERROR: Could not import InfluxDB modules, but InfluxDB host was configured: Can't locate InfluxDB/HTTP.pm in @INC (you may need to install the InfluxDB::HTTP module) (@INC entries checked: .. /usr/share/smokeping /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/smokeping/Smokeping.pm line 4169.

### Reason for change

Make possible InfluxDB export, which is supported by Smokeping by default.

**Comment by homerr** [comment]
Change has been merged in.
