### ISSUE TITLE
[BUG] cannot enable IPv6

### ISSUE THREAD

**Issue by bondskin** [linuxserver/docker-smokeping#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not able to enable IPv6 for this docker container, not as sudo docker or as docker.
I have created the daemon.json file but no luck.

"HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "smokeping_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "smokeping",
                        "smokeping"
                    ],
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null,
                    "NetworkID": "1b01d0a84596938fa88c5187baa1b4faae43e5e02f63ad9712048526a0173eba",
                    "EndpointID": "25c9491fdfb3fba16b8d1a65e3d7531f6474b6629e40b439a5d8cc9faa9edadc",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "smokeping",
                        "74562715c6c5"

### Expected Behavior

I'd like to have IPv4 and IPv6 so that the fping6 is working. 

### Steps To Reproduce

pulled container, started and don't see IPv6

### Environment

```markdown
- OS: bookworm
- How docker service was installed: apt
```

### CPU architecture

arm64

### Docker creation

```bash
---
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MASTER_URL=http://192.168.2.66:8542/smokeping/ #optional
#      - SHARED_SECRET=password #optional
      - CACHE_DIR=/tmp #optional
    volumes:
      - /home/pi/docker/smokeping/config:/config
      - /home/pi/smokeping/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8542:8542
    restart: unless-stopped
```

### Container logs

```bash
/usr/sbin/fping -C 20 -q -B1 -r1 -6 -i10 --iface=eth0 -S::1 ipv6.google.com returned with exit code 1024. run with debug enabled to get more information at /usr/share/smokeping/Smokeping.pm line 1809.
/usr/sbin/fping -C 20 -q -B1 -r1 -6 -i10 --iface=eth0 -S::1 ipv6.google.com returned with exit code 1024. run with debug enabled to get more information at /usr/share/smokeping/Smokeping.pm line 1809.
/usr/sbin/fping -C 20 -q -B1 -r1 -6 -i10 --iface=eth0 -S::1 ipv6.google.com returned with exit code 1024. run with debug enabled to get more information at /usr/share/smokeping/Smokeping.pm line 1809.
```

**Comment by drizuid** [comment]
your daemon.json applies to the default bridge, which should never be used (per docker); your compose deployment automatically creates a custom bridge. Have you confirmed using docker inspect your container is on an ipv6 enabled bridge?

```
 ~ # docker exec -it smokeping fping -C 20 -q -B1 -r1 -6 -i10 --iface=eth0 ipv6.google.com
 ipv6.google.com : 13.0 13.1 14.2 14.1 12.6 13.3 13.4 14.6 12.6 14.6 14.6 12.6 13.8 14.1 12.2 13.8 14.7 12.3 12.9 15.0
```

as this is not a container issue but a mistake in configuring docker ipv6, i will close this.
