### ISSUE TITLE
Include echoping in package

### ISSUE THREAD

**Issue by eric** [linuxserver/docker-smokeping#20]
It would be nice to be able to use other kinds of probes like echoping so that HTTP and HTTPS sites can be tested. The echoping provides this support.

**Comment by sparklyballs** [comment]
echoping looks like a dead project

**Comment by eric** [comment]
What's the right way to check a DNS or HTTP endpoint?

**Comment by cosmocracy** [comment]
+1

**Comment by Helithumper** [comment]
Echoping is the supported method for making HTTP checks in smokeping. Even if it is a dead project, it is still a core part of this tool.
