### ISSUE TITLE
Feature Request: TCPPing Probe (and others?)

### ISSUE THREAD

**Issue by SlothCroissant** [linuxserver/docker-smokeping#21]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Hi LSIO team. Great container! I have a quick request.

The great part of SmokePing is that it is extensible probes - see the [list of probes ](http://oss.oetiker.ch/smokeping/probe/index.en.html) for an idea of what can be done. Unfortunately, this image doesn't allow use of many of these probes, as the base install is very thin. For example, I'm trying to implement the [TCPPing probe](http://oss.oetiker.ch/smokeping/probe/TCPPing.en.html), but TCPPing isn't installed in this image by default and as such it cannot be used.

I can `docker exec` into the container to install it, but that seems like it's against the point of running a docker container for SmokePing. Any chance we can get TCPPing installed (and maybe other probes as you see fit)? Thanks!

**Comment by CHBMB** [comment]
I don't use Smokeping but had a quick look at this.  Is there any reason why you can't create a subdirectory in `/config` like `/config/probes/` and edit the line `binary = /usr/bin/tcpping` to be `binary=/config/probes/tcpping` that would make it persistent.

Perhaps if you could tell us exactly what you're doing now we can look at the best way to try and achieve what you want.

**Comment by ryanborstelmann** [comment]
So the real issue is that `binary = /usr/bin/tcpping` is looking for the TCPPing application itself (installed by `sudo apt install tcpping`, for example). Because this binary isn't installed in the base docker image, the probe cannot be used.

I'm no dockerfile creation expert, but I'm fairly certain it's as simple as adding the install tcpping command, via apt or yum, etc, to the dockerfile. But you guys are the experts on that bit :)

**Comment by aptalca** [comment]
@ryanborstelmann Can you try the following three lines from commandline and see if it works?
`docker exec -it smokeping bash` to exec into the container
`curl -o /usr/bin/tcpping http://www.vdberg.org/~richard/tcpping` to download tcpping
`chmod +x /usr/bin/tcpping` to fix permissions
then you can `exit` and see if it works

Let us know if it works and we'll consider adding it to the container permanently

**Comment by CHBMB** [comment]
Yeah I probably should have mentioned it's not a package.

**Comment by CHBMB** [comment]
No update for two months closing this.

**Comment by rcarmo** [comment]
Even though it is just a shell script, would it be possible to have it baked into the image, just for the sake of consistency and having a simpler install?
