### ISSUE TITLE
Log spam "Network unreachable"

### ISSUE THREAD

**Issue by r2ixuz** [linuxserver/docker-smokeping#31]
My Host OS: Synology DSM 6.1.4-15217 Update 5

I have IPv6 for the whole Synology disabled.

`cat /volume1/@docker/aufs/mnt/12ec748b9d95c20f0cd1a750184e427bf67eb9b5f7617fbd9276e97804113613/var/log/apache2/error.log`

Outputs every second this:

`[Sat Jan 13 11:47:55.929583 2018] [core:warn] [pid 232] (101)Network unreachable: AH00056: connect to listener on [::]:80`

This is with version 94 .

**Comment by thelamer** [comment]
try editing the file: 

/volume1//mnt/12ec748b9d95c20f0cd1a750184e427bf67eb9b5f7617fbd9276e97804113613/etc/apache2/httpd.conf 

And change the line: 
```
Listen 80
```
to
```
Listen 0.0.0.0:80
```
Then restart the container. 

This will force ipv4,  let us know if this works for you.

**Comment by r2ixuz** [comment]
Yes, this fixed it, thanks.

But if I delete the container or upgrade it, this error will come back ;-(

**Comment by thelamer** [comment]
Yeah I am not 100% on the implications of disabling ipv6 by default on the image. If you want make a Pull request and modify this file at this line for the requested change so it can be reviewed by the team: 

https://github.com/linuxserver/docker-smokeping/blob/master/root/etc/apache2/httpd.conf#L62

**Comment by sparklyballs** [comment]
I've made a PR #32 that exposes the apache config file in /config and makes a symlink to the required destination internal of the container

**Comment by sparklyballs** [comment]
actually before going that route 

there is an :unraid tag because at the time unraid didn't support ipv6

@r2ixuz try that before this PR get's merged because it's just dawned on me that the fping tool wouldn't work anyways as it needs compiling to be non ipv6 compatible

**Comment by r2ixuz** [comment]
Doesn't work with LATEST and UNRAID too. Both have "Listen 80".

The error messages starts to spam couple minutes (approx. 3 min) after container start. When this happens, there are 7 more httpd processes visible via "ps aux". I guess something is tries to start another httpd instances which fails, becaus ::80 is already used by the first instance.

IPv6 seems no problem anyway:

`netstat -anp

Active Internet connections (servers and established)                                                             
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name                  
tcp        0      0 :::80                   :::*                    LISTEN      233/httpd                         
tcp        0      0 ::ffff:172.17.0.2:80    ::ffff:172.17.0.1:45173 FIN_WAIT2   -                                 
Active UNIX domain sockets (servers and established)                                                              
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
`
