### ISSUE TITLE
Issue with alpine>3.6 and fping >4.0

### ISSUE THREAD

**Issue by kirek007** [linuxserver/docker-smokeping#33]
Hi, 
I found a problem with latest version (98), there is no graphs. After debugging I found out this:
```
FPing: Got fping output: '(null): can't create raw socket (must run as root?) : Address family not supported by protocol'                         
```
looks like latest fping have a problem with hosts that doesn't support ipv6. Your image is affected because of alpine base (since version 3.6 which includes fping >4.0)
Official fping issue: https://github.com/schweikert/fping/issues/118

To fix it you can downgrade alpine base or update/compile fping manually (patch in attached issue).

**Comment by sparklyballs** [comment]
use the :unraid tag 

it's for hosts that don't have ipv6 support

**Comment by kirek007** [comment]
Thank you :) Looks like yesterday it was to late and I didn't noticed that information in readme.
Have a nice day! :)
