### ISSUE TITLE
fping version in image is broken on systems with ipv6 diabled

### ISSUE THREAD

**Issue by cciechad** [linuxserver/docker-smokeping#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

RHEL 7.5

/usr/sbin/fping -4 8.8.8.8
(null): can't create raw socket (must run as root?) : Address family not supported by protocol

per this it looks like pulling a newer fping would resolve ill see if I can figure out a pull req for it
https://github.com/schweikert/fping/issues/118

**Comment by cciechad** [comment]
I rebased it with edge by changing the following line in the Dockerfile it appears to work with this change although there is probably an easier fix possible.
FROM lsiobase/alpine:3.8
to
FROM lsiobase/alpine:edge

**Comment by homerr** [comment]
Looks like the most recent version is now in Alpine 3.9 so I'll close your PR for now (thank you for it!) and bump this to be moved to Alpine 3.9 in a new issue. Thanks for bringing this to our attention.

**Comment by homerr** [comment]
Didn't spot that this is already rebased to alpine 3.9 so if you pull from :latest your issue should now be fixed. Let us know if not.

**Comment by thelamer** [comment]
Yeah were good in the latest version 
```
docker run --rm -it --entrypoint /bin/bash linuxserver/smokeping
root@9cb1b7562088:/$ fping 8.8.8.8
8.8.8.8 is alive
```
