### ISSUE TITLE
Smokeping - rebase to 3.9

### ISSUE THREAD

**Issue by homerr** [linuxserver/docker-smokeping#60]
This container requires rebase to 3.9 to fix broken fping version in alpine 3.8 

Related issue #55 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by thelamer** [comment]
@homerr we did rebase it to 3.9, are these automated ?

**Comment by homerr** [comment]
Durp. Cheers lamer.
