### ISSUE TITLE
Map Probes Directory to Host Directory

### ISSUE THREAD

**Issue by tonydm** [linuxserver/docker-smokeping#79]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I am trying to expose the Smokeping probes found at /usr/share/perl5/vendor_perl/Smokeping to the host so that a new probe can be installed without the need to copy the new probe into the container.  Which would be lost if the container stops.  Mapping a host ./probes directory to /usr/share/perl5/vendor_perl/Smokeping would make any changes to the probes persistent like the /config/Probes, Targets, etc.
------------------------------

## Expected Behavior
To map the /usr/share/perl5/vendor_perl/Smokeping directory to, for example, /probes.  Similar to how the /config and /data directories are mapped.  This would allow adding a probe without the need to docker cp or another method to update the smokeping config without having to stop and restart the container.

## Current Behavior
Cannot get /usr/share/perl5/vendor_perl/Smokeping to map to host /probes

Host:
services-admin@test:(172.20.0.8)~/DockerServices/docker-smokeping$ ls -alF probes/Smokeping 
lrwxrwxrwx 1 services-admin services-admin 38 Dec  1 23:22 probes/Smokeping -> /usr/share/perl5/vendor_perl/Smokeping

Container:
root@2314b6e23f60:/# ls -alF probes/
total 8
drwxr-xr-x 2 abc  abc  4096 Dec  1 23:22 ./
drwxr-xr-x 1 root root 4096 Dec  1 23:22 ../
lrwxrwxrwx 1 abc  abc    38 Dec  1 23:22 Smokeping -> /usr/share/perl5/vendor_perl/Smokeping/
root@2314b6e23f60:/# ls -alF probes/Smokeping/
total 136
drwxr-xr-x 1 abc  abc   4096 Dec  1 22:20 ./
drwxr-xr-x 1 root root  4096 Dec  1 22:20 ../
-rw-r--r-- 1 abc  abc   3303 May  5  2019 Colorspace.pm
-rw-r--r-- 1 abc  abc    316 May  5  2019 Config.pm
-rw-r--r-- 1 abc  abc  18152 May  5  2019 Examples.pm
-rw-r--r-- 1 abc  abc  14257 May  5  2019 Graphs.pm
-rw-r--r-- 1 abc  abc   6288 May  5  2019 Info.pm
-rw-r--r-- 1 abc  abc   9659 May  5  2019 Master.pm
-rw-r--r-- 1 abc  abc   2084 May  5  2019 RRDhelpers.pm
-rw-r--r-- 1 abc  abc   7276 May  5  2019 RRDtools.pm
-rw-r--r-- 1 abc  abc   5073 May  5  2019 Slave.pm
-rw-r--r-- 1 abc  abc   6408 May  5  2019 ciscoRttMonMIB.pm
drwxr-xr-x 1 abc  abc   4096 Dec  1 22:20 matchers/
-rw-r--r-- 1 abc  abc   3596 May  5  2019 pingMIB.pm
drwxr-xr-x 1 abc  abc   4096 Dec  1 22:20 probes/
drwxr-xr-x 1 abc  abc   4096 Dec  1 22:20 sorters/

## Steps to Reproduce
create a symlink in 30-config (ln -sf /usr/share/perl5/vendor_perl/Smokeping /probes)

docker-compose.yml volumes: - ./probes:/probes

## Environment
Host: ubuntu 19.04
**CPU architecture:** x86_64
docker-ce following prereqs

## Command used to create docker container (run/create/compose/screenshot)
build smokeping -t .

version: "2"
services:
  smokeping:
    image: smokeping
    container_name: smokeping
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Phoenix
    volumes:
      - ./config:/config
      - ./data:/data
      - ./probes:/probes
    ports:
      - 80:80
    restart: unless-stopped

**Comment by thelamer** [comment]
Sorry for the delayed response, my concern here is if we symlink this out then we lock a user into the version of probes when they first spin up the container. ( subsequent updates will not replace the perl scripts in the users config or probes directory as they could be customized) 
Can you think of a way to achieve this without freezing the probes for the user ?

**Comment by IronicBadger** [comment]
@thelamer I agree with you on this one and suggest closing based on that logic.
