### ISSUE TITLE
sSMTP.conf does not apply: Email Alerts do not generate

### ISSUE THREAD

**Issue by cheapstaking** [linuxserver/docker-smokeping#83]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Configured the conf file generated for ssmtp.conf in the docker context as below following guide from https://sendgrid.com/docs/for-developers/sending-email/ssmtp/

mailhub=smtp.sendgrid.net:587
AuthUser={MYsendGRIDUSERNAME}
AuthPass={SENDGRIDPASSWORD}
UseSTARTTLS=YES

DURING container startup error is prompted: 
**smokeping    | cp: cannot stat '/config/smtp.conf': No such file or directory**

------------------------------

## Expected Behavior
The sSMTP.conf in the build context should apply at container startup so sendmail is configured so it can be used for smtp email alerting

## Current Behavior
No emails are sent, instead dead.letter file is generated in the build context

## Steps to Reproduce
1. Startup container
2. Configure sSMTP.config
3. Configure Alerts with TO and FROM Address
4. execute **tSmoke --testmail**

Results in ERROR: not sending mail to myemail@mycompany.com, as all methodes failed

## Environment
Docker-compose

**Comment by cheapstaking** [comment]
When trying to manually configure ssmtp from within the container in /etc/ssmtp/ssmtp.conf and running a test:

root@0a3c1ecfeeb2:/# ssmtp support@cheapstaking.com
To: support@cheapstaking.comcom
From: myemailaddress@gmail.com
Subject: test email

hello world!Segmentation fault
root@0a3c1ecfeeb2:/# hello world!

**Comment by dgraziotin** [comment]
@cheapstaking could you provide a little more explanations, please? I'm having the same issue, but it seems that /etc/ssmtp/ssmtp.conf is correctly populated from the mounted /config/ssmtp.conf. Sending a test e-mail from ssmtp works, but smokeping is not sending through it (same tSmoke error as you report).

**Comment by eddiejdc** [comment]
> @cheapstaking could you provide a little more explanations, please? I'm having the same issue, but it seems that /etc/ssmtp/ssmtp.conf is correctly populated from the mounted /config/ssmtp.conf. Sending a test e-mail from ssmtp works, but smokeping is not sending through it (same tSmoke error as you report).

Did you ever get this resolved? I'm trying to set up email alerts and am having the exact same problem? Is smokeping even compatible with ssmtp?

**Comment by luckman212** [comment]
I am also having the issue. I've configured `ssmtp.conf` and I know it "works" because if I shell into my container with `docker exec -it smokeping bash` and then run `echo "test" | /usr/sbin/ssmtp <my_email@gmail>` I do get the test.

But, in my root dir I see the `dead.letter` file filled with alerts that could not be sent...

**Comment by luckman212** [comment]
I found some relevant links...

- https://lists.oetiker.ch/pipermail/smokeping-users/2019-December/006148.html
- https://github.com/oetiker/SmokePing/issues/123

In the end, I don't know WHY Smokeping/tSmoke was not picking up my configured `sendmail = /usr/sbin/ssmtp` setting from `config/pathnames` but I spent too long scratching my head and in the end I just had to use the sledgehammer.

This "fixes" it by symlinking ssmtp in the default expected sendmail location:
```
docker exec -it smokeping ln -sf /usr/sbin/ssmtp /usr/lib/sendmail
```

**Comment by luckman212** [comment]
I found some relevant links...

- https://lists.oetiker.ch/pipermail/smokeping-users/2019-December/006148.html
- https://github.com/oetiker/SmokePing/issues/123

In the end, I don't know _WHY_ Smokeping/tSmoke was not picking up my configured `sendmail = /usr/sbin/ssmtp` setting from `config/pathnames` but I spent too long scratching my head and in the end I just had to use the sledgehammer.

This "fixes" it by symlinking ssmtp in the default expected sendmail location:
```
docker exec -it smokeping ln -sf /usr/sbin/ssmtp /usr/lib/sendmail
```

@dgraziotin @cheapstaking @thelamer @eddiejdc

**Comment by eddiejdc** [comment]
I never updated this though I should have. 

I wound up doing the exact same thing you did, but over time still had issues with emails alerts breaking frequently for a myriad of issues. This was for a business so we wound up switching to paid software. I still use smokeping at home just without alerts.

**Comment by luckman212** [comment]
I'm using it in the homelab as well. I checked out a number of paid/freemium alternatives too but tbh Smokeping is pretty much perfect for what I was after. Definitely got a few papercuts setting it up (still trying to wrap my head around the alert patterns...)

**Comment by kzaoaai** [comment]
thanks to the symbolic link suggestions. I ended up creating an entrypoint script to automate the command:
```
#!/bin/sh
set -e
ln -sf /usr/sbin/ssmtp /usr/lib/sendmail
exec "$@"
```

and added this to my docker-compose file:
```
    entrypoint: ["/config/entrypoint.sh"]
    command: ["/init"]
```
