### ISSUE TITLE
user authentication to access page?

### ISSUE THREAD

**Issue by daxm** [linuxserver/docker-smokeping#85]
I cannot see how to set up user authentication to limit who can view the Smokeping website.  Is this possible?

**Comment by KetchupBomb** [comment]
While the underlying webserver in this image is Apache _and_ it seems that you could implement your own Apache-style basic authentication in the `httpd.conf` file saved to the `/config` volume, I don't think this is a parameter linuxserver would raise to the Docker environment level.

Instead, consider using a reverse proxy and have _that_ manage your auth when the underlying application doesn't have a first-party supported mechanism. [`nginx-proxy`](https://github.com/nginx-proxy/nginx-proxy) exposes an [environment variable for basic auth](https://github.com/nginx-proxy/nginx-proxy#basic-authentication-support).

**Comment by IronicBadger** [comment]
+1 to the above

**Comment by IronicBadger** [comment]
This issue should probably be closed as won't implement.

**Comment by nemchik** [comment]
Closing as this seems answered. Feel free to ask if you have more questions.
