### ISSUE TITLE
Alert can't work

### ISSUE THREAD

**Issue by shizhao** [linuxserver/docker-smokeping#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Set alert script, but can't work.

## Steps to Reproduce

1. Startup container
2. Configure /config/Alerts:
to = |/config/alert.sh
......
3. Write alert.sh
......
curl 'http://url.com' -d 'some....' >> alert.log 2>&1
......
4. Configure /config/Targets:  alerts = someloss
5. Restart smokeping
6 Wait 1.5 * step time
alert.log is null.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by IronicBadger** [comment]
Please refer to the upstream Smokeping documentation for configuring [Alerts](https://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html#___top) correctly. I don't see an example there for running an arbitrary script upon alert.

However, in this repo there is an example of the correct syntax for performing an alert with Smokeping - https://github.com/catalyst/smokeping-mtr-alert

If you do ever get this working, please let me know. But please note that LSIO provide support for the containers and not necessarily the apps in them - so reaching out to Smokeping might yield better results. Please do post back here if you are successful.
