### ISSUE TITLE
The container state is always create

### ISSUE THREAD

**Issue by nondevops** [linuxserver/docker-smokeping#94]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

The container did not start properly

## Current Behavior

![image](https://user-images.githubusercontent.com/12181410/90140515-6feae580-ddac-11ea-82f9-329b2b322b11.png)

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
`docker start smokeping`
