### ISSUE TITLE
Change server name ?

### ISSUE THREAD

**Issue by EVOTk** [linuxserver/docker-smokeping#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------
## Environment
**OS:**   Raspbian 64
**CPU architecture:** arm64      

## Command used to create docker container (run/create/compose/screenshot)

> version: "2.1"
> services:
>   smokeping:
>     image: linuxserver/smokeping
>     container_name: smokeping
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=Europe/Paris
>     volumes:
>       - /home/pi/Docker/smokeping/config:/config
>       - /home/pi/Docker/smokeping/data:/data
>     ports:
>       - 8080:80
>     restart: unless-stopped

---------------
Hello,
It's possible change the server name ? thx

![2020-09-07 11_48_30-Window](https://user-images.githubusercontent.com/45015615/92374590-3f267380-f100-11ea-8fdd-1eb3eeaea680.png)

**Comment by EVOTk** [comment]
it's okay,
It is to be specified in the compose!

Exemple :

> version: "2"
> services:
>   smokeping:
>     image: linuxserver/smokeping
>     container_name: smokeping
>     hostname: YOURHOSTNAME
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=Europe/Paris
>     volumes:
>       - /home/pi/Docker/smokeping/config:/config
>       - /home/pi/Docker/smokeping/data:/data
>     ports:
>       - 80:80
>     restart: unless-stopped

**Comment by luckman212** [comment]
I didn't know about this either. Guess this is a universal docker thing. Since the hostname is so prominent throughout the Smokeping UI, a short note somewhere wouldn't hurt.
