### ISSUE TITLE
Integrate speed test

### ISSUE THREAD

**Issue by adhawkins** [linuxserver/docker-smokeping#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Integrate the speedtest plugin, as mentioned here:

https://jwigley.com/2019/07/09/monitoring-home-internet-speeds-with-smokeping-and-speedtest/

**Comment by IronicBadger** [comment]
I've asked jwigley to contribute a PR for this request. We'll see how that goes otherwise I might add a PR myself.

https://github.com/jwigley/docker-smokeping-speedtest/issues/1

**Comment by IronicBadger** [comment]
Unfortunately no reply from Jwigley yet but looking at this in more detail I notice it uses the speedtest-cli program. In my personal experienc with this tool it is quite unreliable for accurately determining speeds.

For example, I used [this](https://hub.docker.com/r/roest/docker-speedtest-analyser/) container for a while and the results were wildly unpredictable. Do you have any experience running the Jwildley version? Is it reliable?

**Comment by adhawkins** [comment]
I've run speedtest-cli standalone before, and it always seemed fairly accurate. I'm really only after an indication though. If my 350 MBit/sec broadband drops to 20MBits/sec for a prolonged period then I'd like to know about it. I don't really care if occasionally I get 320 or 380 MBits/sec.

**Comment by adhawkins** [comment]
Been doing some testing with that container, and it does seem like the speedtest results are dramatically lower than I would expect. Wonder if there's some kind of performance hit caused by running it inside docker?

**Comment by IronicBadger** [comment]
@adhawkins yeah it is weird isn't it? Glad it's not just me. I don't know what is causing the performance issues but to be honest, I don't have an appetite to go and figure it out either! If you do, please go ahead. I'm going to suggest to the LSIO team that we close this thread for now, feel free to reopen if you get it working reliably and we'll consider adding this feature to the container. Thanks!

**Comment by deveth0** [comment]
hi, even though this thread is closed, this probably helps:

speedtest-cli seems to use an old endpoint that is deprecated (see https://superuser.com/questions/1434610/speedtest-cli-very-slow-although-network-speed-is-fine). I only get around 500mbit when using this one. 

There is another speedtest container you can use to test, if Docker is limitting: `docker run tamasboros/ookla-speedtest`

This one returns the full bandwidth for me (1000mbit).
